### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by manaspatkar21** [hashicorp/vault-service-broker#19]
I am playing around with vault service broker on my local machine. I have updated the vault.go file.

What are the next steps after updating the vault.go file ? Do I need to deploy the vault broker or do I need to build the broker first ? If so, how to build the broker ?

**Comment by stenio123** [comment]
Hello, you don't need to explicitly build the broker, just clone your repo and push it to Cloud Foundry using its client. Therefore:

In order to use the service broker you need to first have access to a PCF environment.

Once you have that, make sure that you have the cf client and an authenticated session, as described here: https://docs.cloudfoundry.org/cf-cli/getting-started.html

Now following the README instructions, just replace with the Hashicorp github repo with your repository that contains the updated code:
```
Deploy the vault-broker by cloning this repository:

$ git clone https://github.com/YOUR-REPO
$ cd cf-vault-broker
And push to Cloud Foundry:

$ cf push --random-route --no-start
```

**Comment by tyrannosaurus-becks** [comment]
I realize this issue is old and probably no longer needed, but in case other people see it I'd like to also add this comment.

This week I updated the repo's README with more extensive instructions on how to set up a dev environment, and linked to a sample my-app. Please check out the updated README as it has a clear walk-through now on how to build the broker.
